[profile.default]
src             = 'src'                                 # The source directory
out             = 'out'                                 # The output directory
libs            = ['lib']                               # A list of library directories
optimizer       = true                                  # Enable or disable the solc optimizer
optimizer_runs  = 200                                   # The number of optimizer runs
solc_version    = '0.8.24'                              # Override for the solc version
via_ir          = true                                  # Enable IR-based compilation to avoid stack too deep errors
remappings = [
    "agora-governor/=lib/agora-governor/",
    "src/lib/=lib/agora-governor/src/lib/"
]
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
